### ISSUE TITLE
⚡ Standardization of rep

### ISSUE THREAD

**Issue by luxonauta** [dracula/i3lock#1]
Hi @fccapria, we need to adjust a few things first to move forward, ok? ✨

First, we need to update the screenshot!

Can you take a single capture at the closest possible resolution to 1728x1117?

We also need a separate `.md` with installation instructions to show the theme on the site.

I ask for these changes to standardize with the other repositories, [see an example](https://github.com/dracula/notepad-plus-plus); this is also important because it helps other potential users who would like to contribute too! 😁

Let me know if something isn't possible or if you have any questions! 🙂

**Comment by fccapria** [comment]
Hi, of course, I just checked the template you sent me, soon I'll get to work to standardize everything! 😁
I only have one request: the theme is specifically for i3lock-color, the fork that allows you to use a different color scheme than the default of i3lock.
Is it better to change the repo name to 'i3lock-color' or leave it like this? 🤔

**Comment by fccapria** [comment]
Hi @luxonauta, I just finished standardizing the repo. The only "doubt" I had is about the name of the repo as I mentioned in the previous message, but nothing very important. 😁
Let me know what you think, and if I can possibly add more or is it better to leave it clean! 😉

**Comment by luxonauta** [comment]
That's great! 🚀 Everything was ok, I already adhered to your suggestion, too, and I changed the repo's name 😉; soon, I'll take the following steps to include it on the site! 🧛🏻
